### ISSUE TITLE
Angelscript would to have OpenGL 1, 2, 3 and newer, to load dll and to show hud-gui screen

### ISSUE THREAD

**Issue by ghost** [baso88/SC_AngelScript#61]
Is it possible - we have to get OpenGL support - If our map need to load OpenGL specific features like Bump-mapping or VAO, VBO shader etc... Example write own reflection water Angelscript into SC Map.

And loading dll? If we use Bullet 3 dll into Sven Coop than it looks like Source Engine.
Or any dll if we have requirements of dll example Lua or any features

And we would like to have hud gu screen like real Counter Strike Team-Switcher or Half-Life Rally userinterface into hud screen of in-game. PS Sorry I force about hud gui screen because I think what do I like to have hud gui screen. Like example Key unlocker like "1234" or "7117" etc... like key unlocker made Arrangement Mod by SysOp.

Are features for next release of Sven Coop?

**Comment by fnky** [comment]
The way AngelScript is implemented in SC is at a much higher level than rendering level. The only access you'll get is for game objects, already handled by the underlying engine and for good reasons.

As for DLLs, it could be possible but then you should also ask yourself about what the security implications would be and that requires a lot of work. Personally I don't think there would be any benefits, since AMXX/Metamod already supports similar features.

There have been talk about a custom HUD (VGUI) implementation that would be running a browser instance and allows for interoperability via. JavaScript, however this has not been confirmed to be under development in a long time so take it with a grain of pepper.

I hardly believe the the requested features will be implemented any time soon, if at all.

**Comment by ghost** [comment]
Hello @fnky ,

Yes and how do I use OpenGL for Angelscript?

> since AMXX/Metamod already supports similar features.

No AMXX or MetaMod !!! Only Implement like OpenGL32.dll or Bullet3.dll like "Load DLL" from C++/C

For Javascript? Eh that is not Javascript just res like Counter-Strike Team Screen or Buying weapon screen. 
Why do I need Javascript? You mean HTML5 in game? It is really impossible. That is not for HTML5 just C# and resource script / query script.![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313734323232392f3139333234332f33316335366534612d376637652d313165322d393564342d6637306338633839393366352e6a7067](https://user-images.githubusercontent.com/3496136/30743323-67a08678-9f9d-11e7-8c88-158d0bdee1dc.jpg)

Why You say about Javascript? I think you miss understand me. It is not javascript just it is for hud gui screen like I show example of counter strike team screen or transparent gui in hud screen.

**Comment by baso88** [comment]
This is out of the question atm. Client-side scripting will have to go first, and even when that is made available it's unlikely we will expose low-level OpenGL functionality through the AS API.

CEF (Chromium Embedded Framework) based UI and client-side scripting will make custom UI/HUD possible. When the existing renderer is updated from immediate mode we will probably add support for custom shaders, but this will be mostly useful for world rendering, studio model rendering and post-processing.

Since it will take some time to implement the above mentioned CEF-based UI/HUD I've added basic support for custom HUD elements (sprites, numeric and time displays).  This is server-side feature with some client-side effects and will be available when the next update is released (5.15). It will likely be carried over and extended when we switch to CEF.

**Comment by ghost** [comment]
Really with CEF??? I never listen about that. But why we need HTML5 and Javascript via Angelscript. I think It understands hard. Thanks!

**Comment by baso88** [comment]
At the moment we are not 100% sure which languages will be available for client-side scripting.

**Comment by ghost** [comment]
Okay no problem now! Just I leave it. So sad hard to write C++. I can understand. I am working my own with C#. Let's surprise!
